version: '3.9'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ERP
      MYSQL_USER: user_db
      MYSQL_PASSWORD: 1092454457J
      MYSQL_ROOT_PASSWORD: 3113509873Mi
    build:
      context: ./MySql
      dockerfile: Dockerfile
    container_name: mysql_eam
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./Config/mysql:/var/lib/mysql
    hostname: apps_database
    networks:
      - eam_apps
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p3113509873Mi"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ERP?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user_db
      SPRING_DATASOURCE_PASSWORD: 1092454457J
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eam_apps

  adminer:
    image: adminer
    container_name: adminer_wms
    restart: always
    ports:
      - 8080:8080
    networks:
      - eam_apps

networks:
  eam_apps:
    driver: bridge
    name: eam_apps
